Add unit tests for vitestsadd vitests

diff --git a/.github/workflows/build_docker_image_fe_aws_scaramanga.yaml b/.github/workflows/build_docker_image_fe_aws_scaramanga.yaml
--- a/.github/workflows/build_docker_image_fe_aws_scaramanga.yaml
+++ b/.github/workflows/build_docker_image_fe_aws_scaramanga.yaml
@@ -25,6 +25,18 @@ on:
         default: ''
         required: false
         type: string
+      max_num_failed_tests:
+        default: '1'
+        required: true
+        type: string
+      min_percentage_coverage:
+        default: '80'
+        required: true
+        type: string
+      tests_vitests:
+        default: 'false'
+        required: false
+        type: string
     secrets:
       aws_access_key_id_non_prod:
         required: false
@@ -36,7 +48,6 @@ on:
         required: false
       gh_npm_registry_pat:
         required: false
-
 env:
   IMAGE_TAG: ${{ inputs.image_tag }}
   AWS_REGISTRY_PROD: ${{ inputs.aws_registry_prod }}
@@ -44,6 +55,9 @@ env:
   AWS_REPOSITORY: ${{ inputs.aws_repository }}
   DOCKER_FILE: ${{ inputs.docker_file }}
   DOCKER_BUILD_ARGS: ${{ inputs.docker_build_args }}
+  MAX_NUM_FAILED_TESTS: ${{ inputs.max_num_failed_tests }}
+  MIN_PERCENTAGE_COVERAGE: ${{ inputs.min_percentage_coverage }}
+  TESTS_VITEST: ${{ inputs.tests_vitest }}
 jobs:
   job:
     timeout-minutes: 30
@@ -54,6 +68,32 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v3
+
+      - name: Execute UnitTests for vitest
+        if: ${{ env.TESTS_VITEST == 'true' }}
+        run: |
+          npm install
+          
+          coverage=$(node node_modules/vitest/vitest.mjs  run --coverage \
+                     --reporter=json --outputFile=test.json | grep 'All files' |
+                     awk -F'|' '{print $2}' | sed -r 's/\s+//g')
+
+          num_failed_tests=$(cat test.json | jq .numFailedTests)
+
+          if [ "${num_failed_tests}" -ge ${MAX_NUM_FAILED_TESTS} ]; then
+            echo "[ERROR] ${num_failed_tests} Tests Failed!, exit with errlvl 1"
+            exit 1
+          else
+            echo "[INFO] Tests Passed successfully, continue"
+          fi
+
+          if [ "${coverage}" -ge ${MIN_PERCENTAGE_COVERAGE} ]; then
+            echo "[INFO] Coverage passed successfully with ${coverage}%, continue"
+          else
+            echo "[ERROR] Coverage ${coverage} is less than the minimum of ${MIN_PERCENTAGE_COVERAGE}, exit with errlvl 1"
+            exit 1
+          fi
+
 
       - name: Configure AWS Credentials PROD
         uses: aws-actions/configure-aws-credentials@v1
