improve to not wait 10m until timeout error for BackOff

diff --git a/.github/workflows/deploy_k8s_scaramanga.yaml b/.github/workflows/deploy_k8s_scaramanga.yaml
--- a/.github/workflows/deploy_k8s_scaramanga.yaml
+++ b/.github/workflows/deploy_k8s_scaramanga.yaml
@@ -84,7 +84,7 @@ jobs:
       - name: Deploy to k8s
         run: |
           K8S_PATH="./k8s/scaramanga/${DEPLOY_ENV}/projects/${PROJECT_CODE}"
-          TIMEOUT=600s
+          TIMEOUT=180s
 
           kubectl apply -f "${K8S_PATH}/service.yaml"
           kubectl apply -f "${K8S_PATH}/autoscaling.yaml"
@@ -105,4 +105,15 @@ jobs:
           fi
 
           kubectl rollout status deployment ${PROJECT_CODE} --timeout=${TIMEOUT}
+          errlvl=$?
 
+          if [ $errlvl -ne 0 ]; then
+            echo "[ERROR] Something went wrong deploying the new version"
+            kubectl get pods | grep ${PROJECT_CODE}
+
+            echo "[INFO] Getting Deployment Events"
+            kubectl get events | grep -i ${PROJECT_CODE} | grep -vE 'Normal|LoggingDisabled'
+
+            #echo "[INFO] Getting Deployment describe"
+            #kubectl describe pod ${PROJECT_CODE}
+          fi
