error message

diff --git a/.github/workflows/deploy_lambda_scaramanga.yaml b/.github/workflows/deploy_lambda_scaramanga.yaml
--- a/.github/workflows/deploy_lambda_scaramanga.yaml
+++ b/.github/workflows/deploy_lambda_scaramanga.yaml
@@ -41,7 +41,7 @@ jobs:
 
           retries=0;
           status=0;
-          while [ $status != 1 ] || [ $retries -le "30" ]
+          while [ $status != 1 ] || [ $retries -le "300" ]
           do
             status=$(aws lambda get-function \
             --function-name ${PROJECT_CODE} \
@@ -50,4 +50,12 @@ jobs:
             sleep 1s;
             ((retries))
           done
-          echo "[INFO] Function deployed"
+
+          if [ $retries -gt "300" ]
+            echo "[ERROR] Function not deployed yet"
+            aws lambda get-function \
+            --function-name ${PROJECT_CODE} \
+            --query 'Configuration.[LastUpdateStatus]'
+            exit 1
+          else
+            echo "[INFO] Function deployed"
