update sonar

diff --git a/.github/workflows/sonar_finance.yaml b/.github/workflows/sonar_finance.yaml
--- a/.github/workflows/sonar_finance.yaml
+++ b/.github/workflows/sonar_finance.yaml
@@ -255,6 +255,9 @@ jobs:
               echo '[DEBUG] Ensuring wget is installed';
               apt-get update && apt-get install -y wget || { echo '[ERROR] Failed to install wget'; exit 1; }
 
+              echo '[DEBUG] Ensuring gpg is installed';
+              apt-get update && apt-get install -y gpg || { echo '[ERROR] Failed to install gpg'; exit 1; }
+
               # Descargar y agregar la clave GPG usando wget
               echo '[DEBUG] Downloading PHP GPG key with wget';
               wget -q -O- https://packages.sury.org/php/apt.gpg | gpg --dearmor -o /usr/share/keyrings/php-sury.gpg || { 
